apiVersion: apps/v1
kind: Deployment
metadata:
  name: promagent-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: promagent-operator
  template:
    metadata:
      labels:
        name: promagent-operator
    spec:
      serviceAccountName: promagent-operator
      containers:
        - name: promagent-operator
          # Replace this with the built image name
          image: fstab/promagent-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - promagent-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: "default"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "promagent-operator"
